version: "3"
services:
  app:
    build: .
    command: anvil-app-server --app Template2050Calculator --data-dir /anvil-data
    ports:
      - 127.0.0.1:3030:8080
    volumes:
      - ./:/apps/Template2050Calculator
